server:
  port: ${properties.eureka.port}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${properties.eureka.url}
#      default-zone: http://localhost:28761/eureka/,http://localhost:28762/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0

# 不为zipkin提供数据
spring:
  sleuth:
    enabled: false
    sampler:
      percentage: 0.0

management:
  security:
    enabled: false
