server:
  port: ${properties.eureka.port1}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${properties.eureka.hostname1}:${properties.eureka.port1}/eureka/,http://${properties.eureka.hostname2}:${properties.eureka.port2}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0

# 不为zipkin提供数据
spring:
  sleuth:
    sampler:
      percentage: 0.0
