server:
  port: ${properties.springbootadmin.port}

info:
  version: @project.version@

eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:18761/eureka/,http://localhost:18762/eureka/
      defaultZone: ${properties.eureka.url}

# endpoint
management:
  security:
    enabled: false

turbine:
  # turbine HTTP
  # turbine monitor hystrix service
  app-config: ${properties.springbootadmin.turbine.appconfigs}
# app-config: SpringCloudImpl,Search
  # mast be setting cluster name
  cluster-name-expression: ${properties.springbootadmin.turbine.clusternameexpression}
#  cluster-name-expression: "'default'"
#  stream:
#    port: 8989

spring:
  # ignore tracking for zipkin server
  sleuth:
    enabled: false
  boot:
    admin:
      monitor:
        read-timeout: 50000
      routes:
        # hystrix.stream UI(hystrix.stream) / turbine UI(turbine.stream) / activiti UI(activiti)
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,turbine.stream,activiti
      turbine:
        clusters: ${properties.springbootadmin.turbine.clusters}
        # turbine HTTP
        # turbine service id that is spring boot admin service id
        location: ${spring.application.name}
        # turbine stream
#        location: http://localhost:${turbine.stream.port}/

# for log
logging:
  file: ${spring.application.name}