server:
  port: 8010
#  context-path: /springcloud-service
#  port: ${random.int[8010,8020]}

# use pom file properties
info:
  version: @project.version@

eureka:
  # 更改服务实例名字，可以在一个主机中，启动多个端口相同但服务实例名不同的服务。(前提：端口必须不一致)
  instance:
#    instance-id: ${spring.application.name}:${random.int}
    hostname: localhost
  client:
    service-url:
      default-zone: http://${eureka.instance.hostname}:8761/eureka/,http://${eureka.instance.hostname}:8762/eureka/

# endpoint
management:
  security:
    enabled: false

# enable feignClient fallback
feign:
  hystrix:
    enabled: true

turbine:
  # turbine HTTP
  # turbine monitor service
  app-config: ${spring.application.name}
  cluster-name-expression: "'default'"

# spring cloud steam/sleuth
spring:
  rabbitmq:
    host: localhost
    port: 5672
  # http zipkin
#  zipkin:
#    base-url: http://${eureka.instance.hostname}:8020
  sleuth:
    sampler:
      percentage: 1
  cloud:
    # spring cloud stream group (rabbitmq queue)
    stream:
      bindings:
        input:
          context-type: application/json
          # 自定义 rabbitmq Exchanges
          destination: demo
          # rabbitmq Queue Name
          group: springcloud
        output:
          context-type: application/json
          destination: demo
          group: springcloud

# for spring boot admin log tag
logging:
  file: ${spring.application.name}

